services:
  - type: web
    name: jiaveri-jobs
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PHONE
        value: 9999999999
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: 3000
